[bridge]
  port = /dev/ttyUSB0
  channel = Public
  key = 8b3387e9c5cdea6ac9e5edbaa115cd72
  name =  # имя отображается в анонсах  РНС
  announce = 30 # интервал анонсов в минутах, пусто - отключено
  mode = 2 
  auth_password = **** # пароль для авторизации
  news = on # публикация новостей из РНС или эфира
  news_file = /home/orangepi/.reticulum-meshchatx/storage/page_nodes/___папка с файлами страницы NamadNet____/pages/news.mu
  max_news = 50
  news_hash = # хеш личности NomadNet



# === Автоматический маяк ===
  beacon_enabled = on # пустое поле откл.
  beacon_interval = 7200 # интервал маяка с минутах
  beacon_text = 📡 Мост RNS активен. Для связи используйте MeshChat или любой LXMF-клиент.

# === Логирование ===
  log_enabled = on 
  log_retention_days = 7
